import globals from "globals";
import js from "@eslint/js";
import tsEslint from "typescript-eslint";
import pluginReact from "eslint-plugin-react";
import pluginReactHooks from "eslint-plugin-react-hooks";
import pluginNext from "@next/eslint-plugin-next";
import eslintPluginPrettierRecommended from "eslint-plugin-prettier/recommended";
// import prettierPlugin from "eslint-plugin-prettier";

export default tsEslint.config(
  {
    ignores: [
      "node_modules",
      "!.*",
      "**/dist",
      "**/build",
      // Covers `.next` and local variants such as `.next-mine` (see .gitignore).
      // Linting a Next.js build output buries real findings under ~24k
      // generated-file problems and makes `pnpm lint` unusable.
      "**/.next*",
      "**/next-env.d.ts",
      // esbuild output and the vendored SDK bundle in the playgrounds. Both are
      // git-ignored build artifacts (see their .gitignore files) and together
      // accounted for ~3.9k of the repo's lint findings.
      "apps/sdk-playground/**/vendor/**",
      "apps/sdk-playground/ui-gallery/gallery.js",
      "apps/sdk-playground/ui-gallery/gallery.js.map",
      // Workbox/service-worker output generated by the PWA build.
      "apps/frontend/public/sw.js",
      "apps/frontend/public/workbox-*.js",
      // Generated from packages/agent/skills by scripts/generate-skills.mjs.
      // It ships its own file-wide eslint-disable; linting it only produces
      // an "unused disable directive" report.
      "apps/frontend/src/features/marketing/content/skills.generated.ts",
      "**/out",
      "**/coverage",
      "packages/database/generated",
      "apps/frontend/.clerk",
    ],
  },

  {
    extends: [js.configs.recommended, ...tsEslint.configs.recommended],
    files: ["**/*.{js,mjs,cjs,ts,jsx,tsx}"],
    languageOptions: { globals: globals.node },
  },

  // ────────────────────────────────────────────────────────────────────────
  //  Signal over volume
  //  `pnpm lint` is a build gate (CI fails on it), so every rule left at
  //  "error" has to be worth stopping a merge for. The rules below were the
  //  repo's entire lint baseline and none of them describe a defect: they are
  //  style opinions on code that already ships. Off or "warn" here, so a real
  //  finding is never buried under a few hundred stylistic ones.
  //
  //  This is deliberately NOT where correctness lives. The architecture
  //  boundaries (ARCH-001..ARCH-004 below) stay at "error" and at zero.
  // ────────────────────────────────────────────────────────────────────────
  {
    files: ["**/*.{js,mjs,cjs,ts,jsx,tsx}"],
    rules: {
      // Provider payloads, webhook bodies and Prisma JSON columns are genuinely
      // untyped at the boundary. Typing them is worthwhile work, not a merge
      // blocker — and 250-odd of these were drowning out everything else.
      "@typescript-eslint/no-explicit-any": "off",

      // `@ts-expect-error` with a reason is a legitimate escape hatch, and the
      // existing ones are load-bearing.
      "@typescript-eslint/ban-ts-comment": "off",

      // Dead bindings are worth seeing, so keep reporting them — but a leading
      // underscore is the standard way to say "required by the signature,
      // intentionally unused", and an unused `catch (error)` is not a bug.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          args: "after-used",
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
          caughtErrors: "none",
          ignoreRestSiblings: true,
        },
      ],

      // `type Props = {}` and `interface X extends Y {}` are ordinary React
      // and NestJS idioms.
      "@typescript-eslint/no-empty-object-type": "off",

      // Only reachable where a value is already being called dynamically
      // (the MCP tool dispatcher); the surrounding cast is the real type.
      "@typescript-eslint/no-unsafe-function-type": "off",

      // `cond && doThing()` and `a ? b() : c()` are used throughout.
      "@typescript-eslint/no-unused-expressions": [
        "error",
        {
          allowShortCircuit: true,
          allowTernary: true,
          allowTaggedTemplates: true,
        },
      ],

      // An intentionally swallowed error still has to say so, but an empty
      // `catch {}` around a best-effort cleanup is not worth a build failure.
      "no-empty": ["error", { allowEmptyCatch: true }],

      // `function Page({}: Props)` is how Next.js server components declare
      // "no props used yet" while keeping the type.
      "no-empty-pattern": ["error", { allowObjectPatternsAsParameters: true }],

      // Off, not "warn": the two switches that trigger it (the Telnyx call
      // webhook dispatcher and the WhatsApp message mapper) have cases
      // hundreds of lines long, and satisfying the rule means re-indenting
      // them wholesale inside braces. A duplicate binding across cases is a
      // TypeScript error anyway, which is the failure this rule guards.
      "no-case-declarations": "off",
    },
  },

  // The SDK playgrounds are hand-written ES5 browser scripts: they are served
  // as-is from a static host and drive the shipped IIFE bundle, so `var` and
  // bare browser globals are the point, not an oversight.
  {
    files: ["apps/sdk-playground/**/*.js"],
    languageOptions: {
      globals: globals.browser,
      sourceType: "script",
    },
    rules: {
      "no-var": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },

  // CommonJS tooling config that runs outside the bundlers.
  {
    files: ["**/*.config.{js,cjs}", "**/.*rc.{js,cjs}"],
    languageOptions: { globals: globals.node, sourceType: "commonjs" },
    rules: {
      "@typescript-eslint/no-require-imports": "off",
      "no-undef": "off",
    },
  },

  // ────────────────────────────────────────────────────────────────────────
  //  React / Next.js
  //  These globs used to read `apps/{frontend}` and `packages/{components}`.
  //  A brace group with no comma is not expanded, so both matched a literal
  //  directory of that name — i.e. nothing — and every React rule, including
  //  the ones the code disables inline, was silently inactive.
  // ────────────────────────────────────────────────────────────────────────
  {
    files: [
      "apps/frontend/**/*.{js,jsx,ts,tsx}",
      "apps/chatgpt-app/**/*.{js,jsx,ts,tsx}",
      "packages/frontend-shared/**/*.{js,jsx,ts,tsx}",
      "packages/dialer-ui/**/*.{js,jsx,ts,tsx}",
    ],
    languageOptions: { globals: globals.browser },
    extends: [
      pluginReact.configs.flat.recommended,
      // Next.js uses the automatic JSX runtime: importing React to use JSX is
      // neither required nor done anywhere in this codebase.
      pluginReact.configs.flat["jsx-runtime"],
    ],
    plugins: {
      "react-hooks": pluginReactHooks,
      "@next/next": pluginNext,
    },
    settings: {
      react: {
        version: "detect",
      },
    },
    rules: {
      ...pluginNext.configs.recommended.rules,
      ...pluginNext.configs["core-web-vitals"].rules,

      // TypeScript prop types are the contract; propTypes are not used here.
      "react/prop-types": "off",

      // Apostrophes and quotation marks in marketing and legal copy. Escaping
      // them makes the source harder to proofread and changes nothing that
      // renders.
      "react/no-unescaped-entities": "off",

      // Reverse tabnabbing is a real one, and it is auto-fixable.
      "react/jsx-no-target-blank": "error",

      // `playsInline` on <audio>: React forwards it, the rule only whitelists
      // it on <video>.
      "react/no-unknown-property": "warn",
      "react/no-children-prop": "warn",

      // Warn, not error, and deliberately so. Two thirds of the current hits
      // are the rule's naming heuristic misreading TanStack Table's
      // `header:` / `cell:` render props as plain callbacks — they are
      // rendered as components via flexRender, so the hooks inside them are
      // legal. The rest (hooks behind an `if` in the sidebar and header) are
      // real and worth fixing, but they ship today: flagging them should not
      // block an unrelated merge.
      "react-hooks/rules-of-hooks": "warn",

      // A missing dependency is usually a stale closure, occasionally a
      // deliberate "run once". Report it, don't block on it.
      "react-hooks/exhaustive-deps": "warn",
    },
  },

  // TanStack Table column definitions. `header:` and `cell:` are render props
  // — the table calls them through flexRender, so they *are* components and
  // the hooks inside them are legal. The rule only sees a lowercase callback
  // and reports every one of them, which is ~50 of the repo's hits.
  {
    files: ["**/*columns.tsx", "**/columns/*.tsx"],
    rules: {
      "react-hooks/rules-of-hooks": "off",
    },
  },

  // ────────────────────────────────────────────────────────────────────────
  //  Architecture boundaries (see AGENTS.md + docs/engineering/)
  //  These encode rules an agent or a reviewer cannot infer from types.
  //  Keep them additive: a new violation means the layering is being broken,
  //  not that the rule needs relaxing.
  // ────────────────────────────────────────────────────────────────────────

  // ARCH-001 — External provider SDKs live in packages/platform adapters only.
  // Domain services, the API layer and the worker speak Ringee abstractions
  // (TelephonyService, StripeService, AiProviderRegistry), never a vendor SDK.
  {
    files: [
      "packages/services/**/*.{ts,tsx}",
      "apps/backend/**/*.{ts,tsx}",
      "apps/orchestrator/**/*.{ts,tsx}",
    ],
    rules: {
      "@typescript-eslint/no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "telnyx",
              message:
                "Carrier SDKs belong in packages/platform/src/telephony/telnyx. Use TelephonyService instead.",
            },
            {
              name: "@telnyx/webrtc",
              message:
                "The WebRTC client is browser-side only (packages/dialer-core/src/engine).",
            },
            {
              name: "stripe",
              allowTypeImports: true,
              message:
                'Use StripeService from @ringee/platform. Only `import type Stripe from "stripe"` is allowed, for webhook event types.',
            },
            {
              name: "openai",
              message:
                "AI providers live in packages/platform/src/ai and src/ai-agents. Use the AI service / provider registry.",
            },
            {
              name: "@anthropic-ai/sdk",
              message:
                "AI providers live in packages/platform/src/ai-agents/providers. Use the provider registry.",
            },
          ],
        },
      ],
    },
  },

  // ARCH-002 — Prisma is reached through @ringee/database (repositories +
  // re-exported types), never by importing the generated client directly.
  {
    files: [
      "apps/**/*.{ts,tsx}",
      "packages/services/**/*.{ts,tsx}",
      "packages/platform/**/*.{ts,tsx}",
      "packages/frontend-shared/**/*.{ts,tsx}",
      "packages/dialer-*/**/*.{ts,tsx}",
      "packages/agent/**/*.{ts,tsx}",
    ],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@prisma/client",
              message:
                "Import models, enums and Prisma types from @ringee/database (it re-exports @prisma/client).",
            },
          ],
        },
      ],
    },
  },

  // ARCH-003 — Browser bundles must not pull in server-only packages. These
  // carry secrets, Prisma and NestJS; a stray import ships them to the client.
  {
    files: [
      "apps/frontend/**/*.{ts,tsx}",
      "apps/browser-extension/**/*.{ts,tsx}",
      "apps/chatgpt-app/**/*.{ts,tsx}",
      "packages/frontend-shared/**/*.{ts,tsx}",
      "packages/dialer-core/**/*.{ts,tsx}",
      "packages/dialer-sdk/**/*.{ts,tsx}",
      "packages/dialer-ui/**/*.{ts,tsx}",
    ],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: [
                "@ringee/services",
                "@ringee/services/*",
                "@ringee/database",
                "@ringee/database/*",
                "@ringee/configuration",
                "@ringee/configuration/*",
                "@ringee/platform",
                "@ringee/platform/*",
              ],
              message:
                "Server-only package. Browser code talks to the backend over /api (ApiClient) instead.",
            },
          ],
        },
      ],
    },
  },

  // ARCH-004 — Temporal workflow sandbox. workflows.ts is bundled into a
  // deterministic V8 isolate: only @temporalio/workflow may be imported at
  // runtime. Everything else must be a type-only import (erased at compile
  // time). A runtime import here breaks the worker at startup.
  {
    files: ["apps/orchestrator/src/temporal/workflows.ts"],
    rules: {
      "@typescript-eslint/no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@ringee/*", "@nestjs/*", "./activities", "../*"],
              allowTypeImports: true,
              message:
                "Workflow code runs in Temporal's deterministic sandbox. Use `import type` only; runtime work belongs in activities.ts.",
            },
          ],
        },
      ],
    },
  },

  eslintPluginPrettierRecommended,
  // prettierPlugin.config.recommended,
);
