packages:
  - packages/**
  - apps/**
  - "!apps/browser-extension/files/**"

ignoredBuiltDependencies:
  - keytar

overrides:
  "@types/react": 19.0.1
  "@types/react-dom": 19.0.2

strictPeerDependencies: false
