/**
 * The prompt tells the agent which language to speak, and it reads better —
 * and is followed more reliably — as a name than as a locale code.
 */
const LANGUAGE_NAMES: Record<string, string> = {
  en: "English",
  es: "Spanish",
  pt: "Portuguese",
  fr: "French",
  de: "German",
  it: "Italian",
};

/** "es-MX" → "es". Voices are stored as base languages; callers may not be. */
function base(language: string | null | undefined): string {
  return (language ?? "").split("-")[0]!.toLowerCase();
}

export function languageName(language: string | null | undefined): string {
  return LANGUAGE_NAMES[base(language)] ?? "English";
}

/**
 * One phrase per language Ringee curates voices in.
 *
 * A greeting is not generated by the model — the provider speaks it exactly as
 * written — so a single English string opens every call in English no matter
 * which voice or instructions the agent was given.
 */
export type LocalizedPhrase = Record<string, string>;

/** The phrase for this agent's language, falling back to English. */
export function inLanguage(
  phrase: LocalizedPhrase,
  language: string | null | undefined,
): string {
  return phrase[base(language)] ?? phrase.en!;
}

/**
 * The language policy every blueprint states.
 *
 * It lives here because it is a product decision rather than a per-blueprint
 * one: the agent opens in the language its voice speaks and stays there. Someone
 * answering in another language is not a request to switch — only asking is.
 */
export function languageRule(language: string | null | undefined): string[] {
  const name = languageName(language);
  return [
    `Speak ${name}, from the greeting to the last word of the call.`,
    `Stay in ${name} even if the other person answers in another language.`,
    "Change language only if they explicitly ask you to, and change back if",
    "they ask for that.",
  ];
}
