import { createHmac } from "crypto";
import { deriveSdkKey } from "../../sdk/secrets";
import type {
  CarrierConnectionConfig,
  CarrierRegistration,
  CarrierRegistrationState,
} from "../interfaces/carrier-connection";

/**
 * The userinfo Telnyx accepts in an Internal SIP URI (`destination_uri`):
 * letters, digits, hyphens and underscores.
 */
export const UAC_ROUTING_KEY = /^[A-Za-z0-9_-]{1,128}$/;

export interface UacInternalCredentials {
  user_name: string;
  password: string;
}

/**
 * The connection's own Telnyx-side (Internal UAC) credentials. Telnyx requires
 * them — `user_name` 4–32 alphanumerics with a letter among the first five,
 * `password` 8–128 characters — but nothing in Ringee authenticates with them.
 * They are derived from the connection reference with a server key rather than
 * stored: every synchronization can re-apply the same values, a retry after a
 * lost response converges on them, and they never reach the customer.
 */
export function uacInternalCredentials(
  reference: string,
): UacInternalCredentials {
  const key = deriveSdkKey("carrier_uac");
  const derive = (label: string) =>
    createHmac("sha256", key).update(`${label}:${reference}`).digest("hex");
  return {
    user_name: `rgu${derive("user_name").slice(0, 29)}`,
    password: derive("password"),
  };
}

/**
 * The Internal SIP URI for a route key on Ringee's Call Control application:
 * `<userinfo>@<subdomain>.sip.telnyx.com`, without a `sip:` prefix, as Telnyx
 * documents `internal_uac_settings.destination_uri`.
 */
export function uacDestinationUri(routingKey: string, subdomain: string) {
  return `${routingKey}@${subdomain.toLowerCase()}.sip.telnyx.com`;
}

/**
 * The complete desired state of a UAC connection. PATCH is partial, so every
 * field Ringee manages is always sent: an edit of the carrier settings cannot
 * drop the internal routing. `credentials` are sent on create and whenever the
 * connection does not already hold them — a password cannot be read back.
 */
export function uacPayload(
  config: CarrierConnectionConfig,
  destinationUri: string,
  credentials?: UacInternalCredentials,
) {
  return {
    connection_name: config.reference,
    active: true,
    // Ringee's own WebRTC connections dial the PBX through the generated
    // FQDN. `internal` admits only connections on this account; `unrestricted`
    // would let anyone who learns the FQDN place calls through the PBX. The
    // subdomain receive setting is generated by Telnyx and is not accepted in
    // requests, so it is never sent.
    sip_uri_calling_preference: "internal",
    ...(credentials ?? {}),
    internal_uac_settings: { destination_uri: destinationUri },
    external_uac_settings: {
      proxy: config.proxy,
      username: config.username,
      password: config.password,
      transport: config.transport,
      // Documented as `string | null`: null leaves a setting unset on create
      // and clears it on update. An empty string is not a documented value.
      auth_username: config.authUsername ?? null,
      from_user: config.fromUser ?? null,
      outbound_proxy: config.outboundProxy ?? null,
      expiration_sec: config.expirationSec,
    },
  };
}

function record(raw: unknown): Record<string, unknown> {
  return raw && typeof raw === "object" ? (raw as Record<string, unknown>) : {};
}

/**
 * The managed settings a connection read from Telnyx does not hold, by field
 * name only (values can be secrets). Empty when the connection is complete.
 */
export function uacMismatches(
  raw: unknown,
  expected: { reference: string; destinationUri: string; userName: string },
): string[] {
  const data = record(raw);
  const destination = record(data.internal_uac_settings).destination_uri;
  const checks: Array<[string, boolean]> = [
    ["active", data.active === true],
    [
      "sip_uri_calling_preference",
      data.sip_uri_calling_preference === "internal",
    ],
    ["connection_name", data.connection_name === expected.reference],
    ["user_name", data.user_name === expected.userName],
    [
      "internal_uac_settings.destination_uri",
      typeof destination === "string" &&
        destination.replace(/^sips?:/i, "").toLowerCase() ===
          expected.destinationUri.toLowerCase(),
    ],
  ];
  return checks.filter(([, ok]) => !ok).map(([field]) => field);
}

/**
 * The `fqdn` Telnyx generated for a UAC connection — the host other
 * connections on the account dial to reach the PBX. Only a plain DNS name is
 * accepted: never a URI, a port, a path or anything a SIP header could be
 * smuggled through.
 */
export function uacFqdn(raw: unknown): string | null {
  if (typeof raw !== "string" || raw.length > 253) return null;
  const host = raw.toLowerCase();
  return /^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(host)
    ? host
    : null;
}

/**
 * `sip_registration_status` labels, as Telnyx documents the UAC registration
 * states (`registered`, `trying`, `failed`, `unregistering`,
 * `connection_disabled`, `unknown`).
 */
const STATES: Record<string, CarrierRegistrationState> = {
  registered: "registered",
  trying: "trying",
  failed: "failed",
  expired: "failed",
  unregistering: "unregistering",
  "connection disabled": "disabled",
  disabled: "disabled",
};

/** A SIP status line such as `200 OK` or `401 Unauthorized`; nothing else. */
const SIP_RESPONSE = /^[1-6]\d\d(?: [A-Za-z][A-Za-z -]{0,40})?$/;

function label(raw: unknown) {
  return typeof raw === "string"
    ? raw.toLowerCase().replace(/_/g, " ").trim()
    : "";
}

/**
 * The registration `GET /sip_registration_status` reports for a UAC
 * connection (`credential_type=uac_external_credential`), or null when the
 * answer is about another connection. "Registered" is believed only when the
 * status and the `registered` flag agree.
 */
export function mapUacRegistration(
  raw: unknown,
  connectionId: string,
): CarrierRegistration | null {
  const envelope = record(raw);
  const data =
    envelope.data && typeof envelope.data === "object"
      ? record(envelope.data)
      : envelope;
  if (String(data.connection_id ?? "") !== connectionId) return null;
  const status = label(data.sip_registration_status);
  const state = STATES[status] ?? "unknown";
  const response =
    typeof data.last_registration_response === "string" &&
    SIP_RESPONSE.test(data.last_registration_response.trim())
      ? data.last_registration_response.trim()
      : null;
  return {
    status:
      state === "registered" && data.registered !== true ? "unknown" : state,
    // Allowlisted: arbitrary provider text can echo secrets. The PBX's last
    // answer ("401 Unauthorized") is what explains a failed registration.
    providerStatus:
      status in STATES || status === "unknown"
        ? response
          ? `${status} (${response})`
          : status
        : null,
    // Not reported by this endpoint.
    lastRegisteredAt: null,
    ipAddress: null,
    port: null,
    transport: null,
  };
}

export interface UacErrorDiagnostic {
  code: string | null;
  title: string | null;
  detail: string | null;
  pointer: string | null;
}

/** Every value sent under a password-, secret- or token-like key. */
function sentSecrets(value: unknown, found: string[] = []): string[] {
  for (const [key, item] of Object.entries(record(value))) {
    if (/password|secret|token/i.test(key)) {
      if (typeof item === "string" && item) found.push(item);
    } else if (item && typeof item === "object") {
      sentSecrets(item, found);
    }
  }
  return found;
}

/** Shortest secret fragment that withholds a whole text when it is echoed. */
const SECRET_FRAGMENT = 6;

function safeText(raw: unknown, secrets: string[]): string | null {
  if (typeof raw !== "string" || !raw) return null;
  // Control characters would let provider text forge log lines.
  let text = [...raw]
    .map((character) => {
      const code = character.charCodeAt(0);
      return code < 32 || code === 127 ? " " : character;
    })
    .join("");
  for (const secret of secrets) {
    if (secret.length < SECRET_FRAGMENT) {
      if (text.includes(secret)) return "[withheld]";
      continue;
    }
    text = text.split(secret).join("[redacted]");
    // A truncated echo of a secret is still a secret.
    for (let i = 0; i + SECRET_FRAGMENT <= secret.length; i++)
      if (text.includes(secret.slice(i, i + SECRET_FRAGMENT)))
        return "[withheld]";
  }
  return text.slice(0, 300);
}

/**
 * What a failed SIP Attach request can safely say about itself: each error's
 * code, title, detail and the field it points at. Telnyx echoes rejected
 * values in `detail`, and these requests carry SIP passwords, so every secret
 * that was sent is redacted — and text that would still reveal part of one is
 * withheld whole.
 */
export function uacErrorDiagnostics(
  body: unknown,
  sent: unknown,
): UacErrorDiagnostic[] {
  const errors = record(body).errors;
  if (!Array.isArray(errors)) return [];
  const secrets = sentSecrets(sent);
  return errors.slice(0, 10).map((raw) => {
    const item = record(raw);
    const code = String(item.code ?? "");
    const pointer = record(item.source).pointer;
    return {
      code: /^\d{1,10}$/.test(code) ? code : null,
      title: safeText(item.title, secrets),
      detail: safeText(item.detail, secrets),
      pointer:
        typeof pointer === "string" && /^[\w/.[\]-]{1,200}$/.test(pointer)
          ? pointer
          : null,
    };
  });
}
