import type {
  CarrierConnectionConfig,
  CarrierRegistration,
  CarrierRegistrationState,
} from "../interfaces/carrier-connection";

export function uacPayload(config: CarrierConnectionConfig) {
  return {
    connection_name: config.reference,
    active: true,
    // Ringee's own WebRTC connections dial the PBX through the generated
    // FQDN. `internal` admits only connections on this account; `unrestricted`
    // would let anyone who learns the FQDN place calls through the PBX. The
    // subdomain receive setting is generated by Telnyx and is not accepted in
    // requests, so it is never sent.
    sip_uri_calling_preference: "internal",
    external_uac_settings: {
      proxy: config.proxy,
      username: config.username,
      password: config.password,
      transport: config.transport,
      auth_username: config.authUsername ?? "",
      from_user: config.fromUser ?? "",
      outbound_proxy: config.outboundProxy ?? "",
      expiration_sec: config.expirationSec,
    },
  };
}

/**
 * The `fqdn` Telnyx generated for a UAC connection — the host other
 * connections on the account dial to reach the PBX. Only a plain DNS name is
 * accepted: never a URI, a port, a path or anything a SIP header could be
 * smuggled through.
 */
export function uacFqdn(raw: unknown): string | null {
  if (typeof raw !== "string" || raw.length > 253) return null;
  const host = raw.toLowerCase();
  return /^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(host)
    ? host
    : null;
}

const STATES: Record<string, CarrierRegistrationState> = {
  registered: "registered",
  trying: "trying",
  failed: "failed",
  expired: "failed",
  unregistered: "failed",
  unregistering: "unregistering",
  "connection disabled": "disabled",
  disabled: "disabled",
};

export function mapUacRegistration(raw: unknown): CarrierRegistration {
  const envelope =
    raw && typeof raw === "object" ? (raw as Record<string, unknown>) : {};
  // Some API versions wrap the registration a second time.
  const data =
    envelope.data && typeof envelope.data === "object"
      ? (envelope.data as Record<string, unknown>)
      : envelope;
  const label =
    typeof data.status === "string"
      ? data.status.toLowerCase().replace(/_/g, " ").trim()
      : "";
  const date =
    typeof data.last_registration === "string"
      ? new Date(data.last_registration)
      : null;
  return {
    status: STATES[label] ?? "unknown",
    // Allowlist provider status labels: arbitrary provider text can echo secrets.
    providerStatus:
      label in STATES || ["unknown", "not applicable"].includes(label)
        ? label
        : null,
    lastRegisteredAt: date && Number.isFinite(date.getTime()) ? date : null,
    ipAddress:
      typeof data.ip_address === "string" &&
      /^[\da-fA-F:.]{2,45}$/.test(data.ip_address)
        ? data.ip_address
        : null,
    port:
      typeof data.port === "number" &&
      Number.isInteger(data.port) &&
      data.port > 0 &&
      data.port <= 65535
        ? data.port
        : null,
    transport:
      typeof data.transport === "string" &&
      ["UDP", "TCP", "TLS"].includes(data.transport.toUpperCase())
        ? data.transport.toUpperCase()
        : null,
  };
}
