#!/usr/bin/env node
/**
 * Generate the published-skills module served by the public skill routes.
 *
 * The Ringee Agent Skills live in `packages/agent/skills/<name>/SKILL.md` and
 * are the single source of truth — they are what ships in the Claude Code
 * plugin and in the claude.ai skill zips. This script reads those files and
 * emits a committed TypeScript module so the routes can serve the exact same
 * bytes with NO filesystem access at build or request time, which is what keeps
 * them working identically on Vercel and in the `output: 'standalone'` image.
 *
 *   node scripts/generate-skills.mjs   # -> src/features/marketing/content/skills.generated.ts
 *
 * Runs automatically on `pnpm --filter frontend build` (prebuild), so the
 * committed file cannot drift from the skills for more than one commit.
 * Dependency-free.
 */
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const frontendRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const skillsDir = resolve(frontendRoot, '../../packages/agent/skills');
const outFile = join(
  frontendRoot,
  'src/features/marketing/content/skills.generated.ts'
);

/** The umbrella skill: served at `/SKILL.md`; the rest hang off `.well-known`. */
const ENTRY_SKILL = 'ringee';
/** Agent Skills Discovery RFC: 1-64 chars, lowercase alphanumeric + hyphens. */
const NAME_PATTERN = /^[a-z0-9]+(-[a-z0-9]+)*$/;
/** Agent Skills Discovery RFC: descriptions are capped at 1024 characters. */
const MAX_DESCRIPTION = 1024;

function parseFrontmatter(raw, file) {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n/.exec(raw);
  if (!match) throw new Error(`${file}: missing YAML frontmatter`);

  const fields = {};
  for (const line of match[1].split(/\r?\n/)) {
    // Skills use flat, single-line frontmatter; nothing else is expected.
    const field = /^([A-Za-z-]+):\s*(.*)$/.exec(line);
    if (field) fields[field[1]] = field[2].trim();
  }

  const { name, description } = fields;
  if (!name) throw new Error(`${file}: frontmatter is missing 'name'`);
  if (!description)
    throw new Error(`${file}: frontmatter is missing 'description'`);
  if (!NAME_PATTERN.test(name) || name.length > 64)
    throw new Error(`${file}: '${name}' is not a valid skill name`);
  if (description.length > MAX_DESCRIPTION)
    throw new Error(
      `${file}: description is ${description.length} chars (max ${MAX_DESCRIPTION})`
    );

  return { name, description };
}

const directories = readdirSync(skillsDir)
  .filter((entry) => statSync(join(skillsDir, entry)).isDirectory())
  .sort();

if (directories.length === 0)
  throw new Error(`no skills found in ${skillsDir}`);

const skills = directories.map((directory) => {
  const file = join(skillsDir, directory, 'SKILL.md');
  // Read as bytes: the digest published in the discovery index must be the
  // sha256 of exactly what the route serves.
  const bytes = readFileSync(file);
  const body = bytes.toString('utf8');
  const { name, description } = parseFrontmatter(body, file);

  if (name !== directory)
    throw new Error(
      `${file}: name '${name}' does not match folder '${directory}'`
    );

  return {
    name,
    description,
    digest: `sha256:${createHash('sha256').update(bytes).digest('hex')}`,
    body
  };
});

if (!skills.some((skill) => skill.name === ENTRY_SKILL))
  throw new Error(`missing entry skill '${ENTRY_SKILL}' in ${skillsDir}`);

// Entry skill first — it is the one an agent reads when it lands on /SKILL.md.
skills.sort((a, b) =>
  a.name === ENTRY_SKILL
    ? -1
    : b.name === ENTRY_SKILL
      ? 1
      : a.name.localeCompare(b.name)
);

const entries = skills
  .map(
    ({ name, description, digest, body }) => `  {
    name: ${JSON.stringify(name)},
    description: ${JSON.stringify(description)},
    digest: ${JSON.stringify(digest)},
    body: ${JSON.stringify(body)}
  }`
  )
  .join(',\n');

const output = [
  '/* eslint-disable */',
  '// AUTO-GENERATED by apps/frontend/scripts/generate-skills.mjs — do not edit.',
  '// Source of truth: packages/agent/skills/<name>/SKILL.md',
  '// Regenerate with: pnpm --filter frontend generate:skills',
  '',
  '/** One published Agent Skill, ready to serve verbatim. */',
  'export type PublishedSkill = {',
  '  /** Skill identifier, matching the `name` in the SKILL.md frontmatter. */',
  '  readonly name: string;',
  '  /** Frontmatter description — also what the discovery index advertises. */',
  '  readonly description: string;',
  '  /** `sha256:<hex>` of the raw SKILL.md bytes served by the route. */',
  '  readonly digest: string;',
  '  /** The complete SKILL.md, frontmatter included, byte-for-byte. */',
  '  readonly body: string;',
  '};',
  '',
  'export const PUBLISHED_SKILLS: readonly PublishedSkill[] = [',
  entries,
  '];',
  ''
].join('\n');

writeFileSync(outFile, output, 'utf8');
console.log(
  `✓ ${skills.length} skill(s) → ${outFile.replace(`${frontendRoot}/`, '')}`
);
